// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Check your .env file.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  // --- MOCK OVERRIDES FOR PAUSED SUPABASE ---
  if (typeof window !== "undefined") {
    const originalGetSession = client.auth.getSession.bind(client.auth);
    client.auth.getSession = async () => {
      try {
        const res = await originalGetSession();
        if (res.error) throw res.error;
        if (res.data.session) return res;
      } catch (err) {}
      
      const dummyStr = localStorage.getItem("traumaguard_dummy_session");
      if (dummyStr) {
        try {
          const session = JSON.parse(dummyStr);
          return { data: { session }, error: null };
        } catch (e) {}
      }
      return { data: { session: null }, error: null };
    };

    const originalSignInWithPassword = client.auth.signInWithPassword.bind(client.auth);
    client.auth.signInWithPassword = async ({ email, password }) => {
      try {
        const res = await originalSignInWithPassword({ email, password });
        if (res.error && res.error.message.includes("Failed to fetch")) {
          throw res.error;
        }
        return res;
      } catch (err: any) {
        console.warn("Supabase auth failed. Simulating email login...", err);
        const dummySession = {
          access_token: "dummy-token-email",
          token_type: "bearer",
          expires_in: 3600,
          refresh_token: "dummy-refresh-email",
          user: {
            id: "dummy-email-user",
            email: email,
            user_metadata: { full_name: email.split("@")[0] },
            app_metadata: { provider: "email" }
          }
        };
        localStorage.setItem("traumaguard_dummy_session", JSON.stringify(dummySession));
        return { data: { session: dummySession as any, user: dummySession.user as any }, error: null };
      }
    };
    
    const originalSignOut = client.auth.signOut.bind(client.auth);
    client.auth.signOut = async () => {
      localStorage.removeItem("traumaguard_dummy_session");
      return originalSignOut();
    };
  }

  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
