/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
<<<<<<< HEAD
import { Route as AuthenticatedChatHistoryRouteImport } from './routes/_authenticated/chat-history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDoctorsRouteImport } from './routes/_authenticated/doctors'
=======
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDoctorsRouteImport } from './routes/_authenticated/doctors'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated/emergency'
>>>>>>> 60a320c8e08cea17efa61a45f466bf68678a8569
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated/records'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat/index'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat/$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const AuthenticatedChatHistoryRoute =
  AuthenticatedChatHistoryRouteImport.update({
    id: '/chat-history',
    path: '/chat-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
=======
>>>>>>> 60a320c8e08cea17efa61a45f466bf68678a8569
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorsRoute = AuthenticatedDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
<<<<<<< HEAD
=======
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
>>>>>>> 60a320c8e08cea17efa61a45f466bf68678a8569
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
<<<<<<< HEAD
  '/chat-history': typeof AuthenticatedChatHistoryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctors': typeof AuthenticatedDoctorsRoute
=======
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctors': typeof AuthenticatedDoctorsRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
>>>>>>> 60a320c8e08cea17efa61a45f466bf68678a8569
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
<<<<<<< HEAD
  '/chat-history': typeof AuthenticatedChatHistoryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctors': typeof AuthenticatedDoctorsRoute
=======
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctors': typeof AuthenticatedDoctorsRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
>>>>>>> 60a320c8e08cea17efa61a45f466bf68678a8569
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
<<<<<<< HEAD
  '/_authenticated/chat-history': typeof AuthenticatedChatHistoryRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doctors': typeof AuthenticatedDoctorsRoute
=======
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doctors': typeof AuthenticatedDoctorsRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
>>>>>>> 60a320c8e08cea17efa61a45f466bf68678a8569
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
<<<<<<< HEAD
    | '/chat-history'
    | '/dashboard'
    | '/doctors'
=======
    | '/dashboard'
    | '/doctors'
    | '/emergency'
>>>>>>> 60a320c8e08cea17efa61a45f466bf68678a8569
    | '/notifications'
    | '/records'
    | '/reports'
    | '/settings'
    | '/chat/$threadId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
<<<<<<< HEAD
    | '/chat-history'
    | '/dashboard'
    | '/doctors'
=======
    | '/dashboard'
    | '/doctors'
    | '/emergency'
>>>>>>> 60a320c8e08cea17efa61a45f466bf68678a8569
    | '/notifications'
    | '/records'
    | '/reports'
    | '/settings'
    | '/chat/$threadId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
<<<<<<< HEAD
    | '/_authenticated/chat-history'
    | '/_authenticated/dashboard'
    | '/_authenticated/doctors'
=======
    | '/_authenticated/dashboard'
    | '/_authenticated/doctors'
    | '/_authenticated/emergency'
>>>>>>> 60a320c8e08cea17efa61a45f466bf68678a8569
    | '/_authenticated/notifications'
    | '/_authenticated/records'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/_authenticated/chat-history': {
      id: '/_authenticated/chat-history'
      path: '/chat-history'
      fullPath: '/chat-history'
      preLoaderRoute: typeof AuthenticatedChatHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
=======
>>>>>>> 60a320c8e08cea17efa61a45f466bf68678a8569
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctors': {
      id: '/_authenticated/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedDoctorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
<<<<<<< HEAD
=======
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
>>>>>>> 60a320c8e08cea17efa61a45f466bf68678a8569
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
<<<<<<< HEAD
  AuthenticatedChatHistoryRoute: typeof AuthenticatedChatHistoryRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoctorsRoute: typeof AuthenticatedDoctorsRoute
=======
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoctorsRoute: typeof AuthenticatedDoctorsRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
>>>>>>> 60a320c8e08cea17efa61a45f466bf68678a8569
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
<<<<<<< HEAD
  AuthenticatedChatHistoryRoute: AuthenticatedChatHistoryRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoctorsRoute: AuthenticatedDoctorsRoute,
=======
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoctorsRoute: AuthenticatedDoctorsRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
>>>>>>> 60a320c8e08cea17efa61a45f466bf68678a8569
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
